//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string ImageURl { get; set; }
        public string LogoUrl { get; set; }
        public bool isactive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
