//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehicleAmenties = new HashSet<VehicleAmenty>();
            this.VehicleFeatures = new HashSet<VehicleFeature>();
            this.VehicleImages = new HashSet<VehicleImage>();
            this.VehicleRents = new HashSet<VehicleRent>();
            this.VehicleRentleConditions = new HashSet<VehicleRentleCondition>();
            this.OfferMasters = new HashSet<OfferMaster>();
            this.VehicleTags = new HashSet<VehicleTag>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string VehicleCode { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> Sleeps { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public string Length { get; set; }
        public string Width { get; set; }
        public bool IsFeatured { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public bool IsSaleable { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleAmenty> VehicleAmenties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleFeature> VehicleFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleImage> VehicleImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleRent> VehicleRents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleRentleCondition> VehicleRentleConditions { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferMaster> OfferMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleTag> VehicleTags { get; set; }
    }
}
